import json
import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

# Initialize Groq client
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# Fixed list of recurring report categories. Kept as a controlled list rather than freeform AI
# output so the same client's file_type stays stable across uploads and saved mappings don't collide.
# "other" is the deliberate escape hatch for files that don't match a known category.
FILE_TYPE_CATEGORIES = {
    "fixed_assets": "Fixed Assets Register",
    "bank_transactions": "Bank Transactions",
    "payroll": "Payroll",
    "general_ledger": "General Ledger",
    "accounts_receivable": "Accounts Receivable",
    "accounts_payable": "Accounts Payable",
    "inventory": "Inventory",
    "other": "Other",
}

# Main function to detect columns using LLM
def detect_columns_with_llm(columns: list, sample_values: dict = None, fill_rates: dict = None) -> dict:
    """
    Send column names, sample values and fill rates to Groq LLM for detection.
    LLM maps each column to its standard financial meaning AND field type.
    fill_rates tells the LLM how many rows have data in each column.
    Columns with very low fill rates are mapped to unknown.
    """
    # Normalize columns to lowercase for LLM.Keep a mapping of lowercase → original so we can restore later
    lower_to_original = {}
    for col in columns:
        lower_to_original[col.lower().strip()] = col
    lowercase_columns = list(lower_to_original.keys())

    # Normalize sample values keys to lowercase too
    lowercase_samples = {}
    if sample_values:
        for col, val in sample_values.items():
            lowercase_samples[col.lower().strip()] = val
    # Normalize fill rates keys to lowercase too
    lowercase_fill_rates = {}
    if fill_rates:
        for col, rate in fill_rates.items():
            lowercase_fill_rates[col.lower().strip()] = rate
    # Build column context for LLM including name, sample value and fill rate
    columns_context = json.dumps([
        {
            "column": col,
            "sample": str(lowercase_samples.get(col, "")),
            "fill_rate": lowercase_fill_rates.get(col, 1.0)
        }
        for col in lowercase_columns
    ])
    columns_instruction = "Column names, a sample value and fill rate (percentage of rows with data) from the uploaded file:"
    prompt = f"""You are a financial data expert helping an audit firm.

Your job is to map Excel column names to their standard financial meaning
and classify each column into a field type.

{columns_instruction}
{columns_context}

Instructions:
- Map each column to a simple lowercase snake_case standard financial field name
- Also classify each column into exactly one of these field types:
  "numeric"  → any column containing amounts, costs, balances, salaries, tax, depreciation
  "date"     → any column containing dates
  "text"     → any column containing names, descriptions, status, references, codes
  "unknown"  → genuinely cannot determine the field type
- Use the sample value as a context clue when the column name is ambiguous
- Use the fill_rate as a signal:
  If fill_rate is below 0.20 (less than 20% of rows have data) → map to "unknown"
  A column with almost no data is likely meaningless or auto-generated by Excel
- Stay strictly within financial and accounting context
- Use your financial knowledge to map every column confidently
- Only use "unknown" as a last resort for truly meaningless columns
- For columns mapped to "unknown", still provide a best-guess "suggestion" in lowercase snake_case — what this column might be based on the sample value and column name. This helps the auditor know what to type if they want to fix it manually.
- Return ONLY a valid JSON object — no text before or after

Example output format:
{{
  "date": {{"mapped_to": "date", "field_type": "date"}},
  "amt": {{"mapped_to": "amount", "field_type": "numeric"}},
  "vendor name": {{"mapped_to": "vendor", "field_type": "text"}},
  "unnamed: 15": {{"mapped_to": "unknown", "field_type": "unknown", "suggestion": "payment_status"}}
}}"""
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": "You are a financial data mapping assistant for an audit firm. You only return valid JSON. No explanations. No markdown. No backticks."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0,
        max_tokens=2000,
    )
    # Parse LLM response
    raw = response.choices[0].message.content.strip()
    raw = raw.replace("```json", "").replace("```", "").strip()
    try:
        lowercase_mapping = json.loads(raw)
    except json.JSONDecodeError:
        # If LLM returns invalid JSON mark all as unknown
        lowercase_mapping = {
            col: {"mapped_to": "unknown", "field_type": "unknown"}
            for col in lowercase_columns
        }
    # Map results back to original column names
    final_mapping = {}
    for lower_col, original_col in lower_to_original.items():
        result = lowercase_mapping.get(lower_col, {})
        # Extract mapped_to, field_type and suggestion
        mapped_to = result.get("mapped_to", "unknown")
        field_type = result.get("field_type", "unknown")
        suggestion = result.get("suggestion", "")
        # Make sure all are strings
        if not isinstance(mapped_to, str):
            mapped_to = "unknown"
        if not isinstance(field_type, str):
            field_type = "unknown"
        if not isinstance(suggestion, str):
            suggestion = ""
        # Validate field_type is one of the 4 allowed values
        if field_type not in ["numeric", "date", "text", "unknown"]:
            field_type = "unknown"

        # Extra safety, if fill_rate is below 0.20 force unknown.This catches cases where LLM ignores the fill_rate instruction.
        # suggestion is kept even when forcing unknown, since it's still useful context for the auditor to see
        # what the LLM guessed before the fill_rate override kicked in
        col_fill_rate = lowercase_fill_rates.get(lower_col, 1.0)
        if col_fill_rate < 0.20:
            mapped_to = "unknown"
            field_type = "unknown"

        final_mapping[original_col] = {
            "mapped_to": mapped_to,
            "field_type": field_type,
            "suggestion": suggestion
        }
    return final_mapping

# Suggest which recurring report category a file belongs to, based on its column names and sample values.
# Returns one of the keys in FILE_TYPE_CATEGORIES, defaulting to "other" if nothing matches confidently.
# This is a classification task (pick from a fixed list) rather than open-ended generation, so the LLM
# is constrained to the same categories every time, keeping a client's saved mappings stable across uploads.
def suggest_file_type(columns: list, sample_values: dict = None) -> dict:
    """
    Send column names and sample values to the LLM and ask it to classify the file
    into one of the fixed FILE_TYPE_CATEGORIES. Returns a dict with the suggested
    category key and a plain-language label for display on the frontend.
    """
    sample_values = sample_values or {}
    # Build a compact context of column names with their sample value for classification
    columns_context = json.dumps([
        {"column": col, "sample": str(sample_values.get(col, ""))}
        for col in columns
    ])
    # Build the list of allowed categories for the prompt so the LLM can only pick from these
    allowed_keys = list(FILE_TYPE_CATEGORIES.keys())

    prompt = f"""You are a financial data expert helping an audit firm classify an uploaded file.

Based on the column names and sample values below, classify this file into exactly
ONE of these categories: {allowed_keys}

Column names and sample values:
{columns_context}

Instructions:
- Pick the single best matching category from the list above
- Use "other" only if the columns genuinely do not match any of the other categories
- Return ONLY a valid JSON object in this exact format, no text before or after:
{{"file_type": "fixed_assets"}}"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": "You are a financial data classification assistant for an audit firm. You only return valid JSON. No explanations. No markdown. No backticks."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0,
        max_tokens=100,
    )
    raw = response.choices[0].message.content.strip()
    raw = raw.replace("```json", "").replace("```", "").strip()
    try:
        result = json.loads(raw)
        file_type = result.get("file_type", "other")
    except json.JSONDecodeError:
        file_type = "other"

    # Validate the returned value is actually one of the allowed categories.
    # Guards against the LLM inventing a new key outside the fixed list
    if file_type not in FILE_TYPE_CATEGORIES:
        file_type = "other"

    return {
        "file_type": file_type,
        "file_type_label": FILE_TYPE_CATEGORIES[file_type]
    }

# Build a comprehensive result including warnings for unknown columns
def build_detection_result(columns: list, final_mapping: dict, sample_values: dict = None, fill_rates: dict = None) -> dict:
    """
    Build the full detection result with warnings.
    A column is unknown if either mapped_to or field_type is unknown.
    sample_values and fill_rates are attached to each column's entry so the frontend
    has enough context per row for the auditor to review unknown or low-confidence columns
    without needing a separate API call.
    """
    # Attach sample_value and fill_rate to every column's mapping entry.
    # Defaults to empty string / 1.0 if not provided so existing calls without these args still work
    sample_values = sample_values or {}
    fill_rates = fill_rates or {}
    enriched_mapping = {}
    for col, info in final_mapping.items():
        enriched_mapping[col] = {
            **info,
            "sample_value": sample_values.get(col, ""),
            "fill_rate": fill_rates.get(col, 1.0)
        }

    unknown_columns = [
        col for col, info in enriched_mapping.items()
        if info.get("mapped_to") == "unknown" or info.get("field_type") == "unknown"
    ]
    warnings = []
    if unknown_columns:
        warnings.append({
            "type": "unknown_columns",
            "message": f"{len(unknown_columns)} column(s) could not be detected: {unknown_columns}",
            "action": "Please map these manually in the next step."
        })
        # Show warning for each unknown column
    return {
        "total_columns": len(columns),
        "mapping": enriched_mapping,
        "unknown_count": len(unknown_columns),
        "warnings": warnings,
        "requires_manual_mapping": len(unknown_columns) > 0
    }
def suggest_file_type(columns_list, sample_values=None):
    """
    Suggest the type of financial file based on column names.
    """
    cols = [str(c).lower() for c in columns_list]

    if any(x in cols for x in ["vendor", "supplier", "invoice_number"]):
        return "accounts_payable"

    if any(x in cols for x in ["customer", "client", "sales"]):
        return "accounts_receivable"

    if any(x in cols for x in ["employee", "salary", "payroll"]):
        return "payroll"

    if any(x in cols for x in ["account", "debit", "credit", "balance"]):
        return "general_ledger"

    return "unknown"
