import json
import os
from groq import Groq
from dotenv import load_dotenv

load_dotenv()

# Initialize Groq client
client = Groq(api_key=os.environ.get("GROQ_API_KEY"))

# Main function to detect columns using LLM
def detect_columns_with_llm(columns: list, sample_values: dict = None, fill_rates: dict = None) -> dict:
    """
    Send column names, sample values and fill rates to Groq LLM for detection.
    LLM maps each column to its standard financial meaning AND field type.
    fill_rates tells the LLM how many rows have data in each column.
    Columns with very low fill rates are mapped to unknown.
    """
    # Normalize columns to lowercase for LLM.Keep a mapping of lowercase → original so we can restore later
    lower_to_original = {}
    for col in columns:
        lower_to_original[col.lower().strip()] = col
    lowercase_columns = list(lower_to_original.keys())

    # Normalize sample values keys to lowercase too
    lowercase_samples = {}
    if sample_values:
        for col, val in sample_values.items():
            lowercase_samples[col.lower().strip()] = val
    # Normalize fill rates keys to lowercase too
    lowercase_fill_rates = {}
    if fill_rates:
        for col, rate in fill_rates.items():
            lowercase_fill_rates[col.lower().strip()] = rate
    # Build column context for LLM including name, sample value and fill rate
    columns_context = json.dumps([
        {
            "column": col,
            "sample": str(lowercase_samples.get(col, "")),
            "fill_rate": lowercase_fill_rates.get(col, 1.0)
        }
        for col in lowercase_columns
    ])
    columns_instruction = "Column names, a sample value and fill rate (percentage of rows with data) from the uploaded file:"
    prompt = f"""You are a financial data expert helping an audit firm.

Your job is to map Excel column names to their standard financial meaning
and classify each column into a field type.

{columns_instruction}
{columns_context}

Instructions:
- Map each column to a simple lowercase snake_case standard financial field name
- Also classify each column into exactly one of these field types:
  "numeric"  → any column containing amounts, costs, balances, salaries, tax, depreciation
  "date"     → any column containing dates
  "text"     → any column containing names, descriptions, status, references, codes
  "unknown"  → genuinely cannot determine the field type
- Use the sample value as a context clue when the column name is ambiguous
- Use the fill_rate as a signal:
  If fill_rate is below 0.20 (less than 20% of rows have data) → map to "unknown"
  A column with almost no data is likely meaningless or auto-generated by Excel
- Stay strictly within financial and accounting context
- Use your financial knowledge to map every column confidently
- Only use "unknown" as a last resort for truly meaningless columns
- Return ONLY a valid JSON object — no text before or after

Example output format:
{{
  "date": {{"mapped_to": "date", "field_type": "date"}},
  "amt": {{"mapped_to": "amount", "field_type": "numeric"}},
  "vendor name": {{"mapped_to": "vendor", "field_type": "text"}},
  "unnamed: 15": {{"mapped_to": "unknown", "field_type": "unknown"}}
}}"""
    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[
            {
                "role": "system",
                "content": "You are a financial data mapping assistant for an audit firm. You only return valid JSON. No explanations. No markdown. No backticks."
            },
            {
                "role": "user",
                "content": prompt
            }
        ],
        temperature=0,
        max_tokens=2000,
    )
    # Parse LLM response
    raw = response.choices[0].message.content.strip()
    raw = raw.replace("```json", "").replace("```", "").strip()
    try:
        lowercase_mapping = json.loads(raw)
    except json.JSONDecodeError:
        # If LLM returns invalid JSON mark all as unknown
        lowercase_mapping = {
            col: {"mapped_to": "unknown", "field_type": "unknown"}
            for col in lowercase_columns
        }
    # Map results back to original column names
    final_mapping = {}
    for lower_col, original_col in lower_to_original.items():
        result = lowercase_mapping.get(lower_col, {})
        # Extract mapped_to and field_type
        mapped_to = result.get("mapped_to", "unknown")
        field_type = result.get("field_type", "unknown")
        # Make sure both are strings
        if not isinstance(mapped_to, str):
            mapped_to = "unknown"
        if not isinstance(field_type, str):
            field_type = "unknown"
        # Validate field_type is one of the 4 allowed values
        if field_type not in ["numeric", "date", "text", "unknown"]:
            field_type = "unknown"

        # Extra safety, if fill_rate is below 0.20 force unknown.This catches cases where LLM ignores the fill_rate instruction
        col_fill_rate = lowercase_fill_rates.get(lower_col, 1.0)
        if col_fill_rate < 0.20:
            mapped_to = "unknown"
            field_type = "unknown"

        final_mapping[original_col] = {
            "mapped_to": mapped_to,
            "field_type": field_type
        }
    return final_mapping

# Build a comprehensive result including warnings for unknown columns
def build_detection_result(columns: list, final_mapping: dict) -> dict:
    """
    Build the full detection result with warnings.
    A column is unknown if either mapped_to or field_type is unknown.
    """
    unknown_columns = [
        col for col, info in final_mapping.items()
        if info.get("mapped_to") == "unknown" or info.get("field_type") == "unknown"
    ]
    warnings = []
    if unknown_columns:
        warnings.append({
            "type": "unknown_columns",
            "message": f"{len(unknown_columns)} column(s) could not be detected: {unknown_columns}",
            "action": "Please map these manually in the next step."
        })
        # Show warning for each unknown column
    return {
        "total_columns": len(columns),
        "mapping": final_mapping,
        "unknown_count": len(unknown_columns),
        "warnings": warnings,
        "requires_manual_mapping": len(unknown_columns) > 0
    }

